[build-system]
requires = ["setuptools", "cython", "numpy", "pysam"]
build-backend = "setuptools.build_meta"

[project]
name = "pairtools"
dynamic = ['version', 'authors',  'license', 'urls', 'description', 'keywords', 'classifiers']
requires-python = ">=3.8"

[tool.cibuildwheel.linux]
before-all = "yum install bzip2-devel xz-devel -y"