[build-system]
requires = ["setuptools", "cython", "numpy", "pysam"]
build-backend = "setuptools.build_meta"

# [project]
# name = "pairtools"
# dynamic = ['version', 'description', 'author', 'author_email', 'url', 'license', 'keywords', 'classifiers', 'long_description', 'long_description_content_type']
# requires-python = ">=3.8"

[tool.cibuildwheel.linux]
before-all = "yum install bzip2-devel xz-devel -y"