[build-system]
requires = ["setuptools", "cython", "numpy", "pysam"]
build-backend = "setuptools.build_meta"

[project]
name = "pairtools"
dynamic = ['version', 'author', 'author_email', 'license', 'url', 'description', 'keywords', 'classifiers']
requires-python = ">=3.8"

[tool.cibuildwheel.linux]
before-all = "yum install bzip2-devel xz-devel -y"