# # This workflow will upload a Python Package using Twine when a release is created
# # For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# name: Upload Python Package

# on:
#   release:
#     types: [created]

# jobs:
#   deploy:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v2
#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.10'
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install setuptools wheel twine cython pysam numpy
#     - name: Build and publish
#       env:
#         TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
#         TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
#       run: |
#         python setup.py sdist
#         twine upload dist/*


name: Publish Python Package to PyPI

on:
  # release:
  #   types: [published]
  workflow_dispatch:

jobs:
  publish_all:
    name: Publish wheels and sdist to PyPI
    
    # if: github.repository == 'open2c/pairtools'
    # if: github.event_name == 'release' && github.event.action == 'published'
    
    # environment: pypi
    # permissions:
    #   id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: dawidd6/action-download-artifact@v7
        with:
          # Required, if the repo is private a Personal Access Token with `repo` scope is needed or GitHub token in a job where the permissions `action` scope set to `read`
          #github_token: ${{secrets.GITHUB_TOKEN}}
          # Optional, workflow file name or ID
          # If not specified, will be inferred from run_id (if run_id is specified), or will be the current workflow
          workflow: python-build-wheels.yml
          # Optional, the status or conclusion of a completed workflow to search for
          # Can be one of a workflow conclusion:
          #   "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
          # Or a workflow status:
          #   "completed", "in_progress", "queued"
          # Use the empty string ("") to ignore status or conclusion in the search
          workflow_conclusion: success

      # - name: Publish distribution 📦 to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1

# jobs:
#   publish_all:
#     name: Publish wheels and sdist to PyPI
#     needs: [build_wheels, make_sdist]
    
#     if: github.repository == 'open2c/pairtools'
#     #if: github.event_name == 'release' && github.event.action == 'published'
    
#     environment: pypi
#     permissions:
#       id-token: write
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/download-artifact@v4
#         with:
#           pattern: cibw-*
#           path: dist
#           merge-multiple: true

#       - name: Publish distribution 📦 to PyPI
#         uses: pypa/gh-action-pypi-publish@release/v1

  # Publish:
    # prevents this action from running on forks
    # if: github.repository == 'open2c/pairtools'
    # runs-on: ubuntu-latest
    # permissions:
    #   id-token: write

    # steps:
    #   - name: Checkout
    #     uses: actions/checkout@v4

    #   - name: Setup
    #     uses: actions/setup-python@v5
    #     with:
    #       python-version: "3.x"
    #       cache: 'pip' # caching pip dependencies
          
    #   - name: Install, build
    #     run: |
    #       python -m pip install --upgrade pip wheel setuptools build
    #       python -m pip install --upgrade cython pysam
    #       python -m pip install -r requirements-dev.txt
    #       python -m build



